# -*- coding: utf-8 -*-
"""Desarrollo de predicados.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EpMAPWvwAqWP0-KCfqSn8Zx4f6himLx3
"""

universo = {
    "alumnos": {
        "Mariana",
        "Doris",
        "Javier",
        "Ana"
    },

    "materias": {
        "Programación",
        "Matemáticas",
        "Química",
        "Redes",
        "Inglés"
    },

    "profesores": {
        "Mario",
        "Elena",
        "Cristina",
        "Maria",
        "Ricardo"
    },

    "dias": {
        "Lunes",
        "Martes",
        "Miércoles",
        "Jueves"
    },

    "horarios": {
        4,
        5,
        6,
        7,
        8,
        9,
        10
    },

    "salones": {
        207,
        208,
        209,
        210,
        211
    },

    "grupos": {
        "7SE",
        "7SF"
    },

    "inscritos": {
        ("Javier", "7SE"),
        ("Mariana", "7SE"),
        ("Doris", "7SF"),
        ("Ana", "7SF")
    },

    "cursan": {
        ("Mariana", "Programación"),
        ("Doris", "Matemáticas"),
        ("Javier", "Química"),
        ("Ana", "Redes")
    },

    "horarios_materia": {
        ("Redes", 8),
        ("Programación", 4),
        ("Matemáticas", 5),
        ("Química", 6),
        ("Inglés", 7)
    },

    "imparten": {
        ("Elena", "Matemáticas"),
        ("Mario", "Programación"),
        ("Cristina", "Química"),
        ("Maria", "Redes"),
        ("Ricardo", "Inglés")
    },

    "clases": {
        ("Javier", "Lunes"),
        ("Mariana", "Martes"),
        ("Doris", "Miércoles"),
        ("Ana", "Jueves")
    },

    "asignados": {
        ("Inglés", "7SF"),
        ("Programación", "7SE"),
        ("Matemáticas", "7SE")
    },

    "se_imparten": {
        ("Química", "Martes"),
        ("Programación", "Lunes"),
        ("Redes", "Miércoles"),
        ("Matemáticas", "Jueves")
    },

    "ubicaciones": {
        ("7SE", 207),
        ("7SF", 208)
    }
}

def alumno(x):
    return x in universo["alumnos"]

def profesor(x):
    return x in universo["profesores"]

def salon(x):
    return x in universo["salones"]

def dia(x):
    return x in universo["dias"]

def horario(x):
    return x in universo["horarios"]

def grupo(x):
    return x in universo["grupos"]

def materia(x):
    return x in universo["materias"]

print(alumno("Mariana"))
print(alumno("Elena"))

print(profesor("Elena"))
print(profesor("Mariana"))

print(salon(207))
print(salon("7SE"))

print(dia("Jueves"))
print(dia("Viernes"))

print(horario(6))
print(horario("Lunes"))

print(grupo("7SE"))
print(grupo("7"))

print(materia("Química"))
print(materia("Pintura"))